"use client";

import Link from "next/link";
import { useState } from "react";
import { useTransactionPreferences } from "@/context/transaction-preferences-context";
import { useUserSettings } from "@/context/user-settings-context";
import { APP_ROUTES } from "@/config/app-routes";

export function TradeSettings() {
  const [open, setOpen] = useState(false);
  const prefs = useTransactionPreferences();
  const { settings, updateSettings } = useUserSettings();
  return <div className="relative"><button type="button" onClick={()=>setOpen(value=>!value)} className="pc-button-light rounded-xl px-3 py-2 text-xs font-semibold" aria-expanded={open}>Workspace settings</button>{open?<div className="pc-review-sheet absolute right-0 top-11 z-40 w-[min(350px,calc(100vw-2rem))] rounded-2xl p-4"><div className="flex items-center justify-between"><h3 className="text-sm font-semibold">Transaction workspace</h3><button type="button" onClick={()=>setOpen(false)} className="text-xs text-slate-500">Close</button></div><fieldset className="mt-4"><legend className="text-xs font-semibold">Default swap network</legend><div className="mt-2 grid grid-cols-2 gap-2">{(["SOLANA","SUI"] as const).map(chain=><button key={chain} type="button" onClick={()=>prefs.setDefaultSwapChain(chain)} className={`rounded-xl border px-3 py-2 text-xs font-semibold ${prefs.defaultSwapChain===chain?"border-[#6d897c] bg-[#eef2ef] dark:bg-white/[.08]":"border-slate-200 dark:border-white/10"}`}>{chain==="SOLANA"?"Solana":"Sui"}</button>)}</div></fieldset><fieldset className="mt-4"><legend className="text-xs font-semibold">Default bridge direction</legend><div className="mt-2 grid grid-cols-2 gap-2">{(["SUI_TO_SOLANA","SOLANA_TO_SUI"] as const).map(direction=><button key={direction} type="button" onClick={()=>updateSettings({bridge:{...settings.bridge,defaultDirection:direction}})} className={`rounded-xl border px-3 py-2 text-xs font-semibold ${settings.bridge.defaultDirection===direction?"border-[#6d897c] bg-[#eef2ef] dark:bg-white/[.08]":"border-slate-200 dark:border-white/10"}`}>{direction==="SUI_TO_SOLANA"?"Sui → Solana":"Solana → Sui"}</button>)}</div></fieldset><label className="mt-4 flex items-start gap-3"><input type="checkbox" checked={prefs.showAdvancedRouting} onChange={event=>prefs.setShowAdvancedRouting(event.target.checked)} className="mt-0.5"/><span><span className="block text-xs font-semibold">Advanced routing context</span><span className="block text-[11px] text-slate-500">Show provider and pool diagnostics. Never changes the wallet signing boundary.</span></span></label><Link href={APP_ROUTES.settings} onClick={()=>setOpen(false)} className="pc-button-light mt-4 flex min-h-10 items-center justify-center rounded-xl px-3 text-xs font-semibold">All settings · RPC & APIs</Link></div>:null}</div>;
}
