"use client";
import { TransactionCompleted } from "@/components/transactions/completed";
import { TransactionMessage } from "@/components/transactions/messages";
import { useEffect,useMemo,useRef,useState } from "react";
import { VersionedTransaction } from "@solana/web3.js";
import { useConnectedWallets } from "@/lib/wallet/connected-wallets";
import { useTrustedTokens } from "@/hooks/use-trusted-tokens";
import { usePortfolio } from "@/hooks/use-portfolio";
import { TokenSelector } from "@/components/assets/token-selector";
import { formatTokenAmount,toTokenBaseUnits,tokensForChain,type TrustedToken } from "@/lib/tokens/trusted-token-list";
import { useSlippageTolerance } from "@/hooks/use-slippage-tolerance";
import { SWAP_SLIPPAGE_PRESETS_BPS, formatSwapSlippagePercent } from "@powerchain/swap-core";
import { apiFetch } from "@/lib/api/browser-api";
import { solscanTransactionUrl } from "@/lib/explorers/links";
import { useUserSettings } from "@/context/user-settings-context";

type Order={provider:"jupiter";requestId:string;transaction:string;inputMint:string;outputMint:string;inAmount:string;outAmount:string;otherAmountThreshold?:string;priceImpactPct?:string;router?:string;gasless?:boolean;expireAt?:string|null;lastValidBlockHeight?:number|null;routePlan?:unknown[];payer:string;userPaysNetworkFees:true};
function unwrap<T>(value:unknown):T|null{return value&&typeof value==="object"&&"data" in value?(value as {data?:T}).data??null:null}
function apiErrorCode(value:unknown,fallback:string){if(!value||typeof value!=="object")return fallback;const error=(value as {error?:unknown}).error;if(!error||typeof error!=="object")return fallback;const code=(error as {code?:unknown}).code;return typeof code==="string"&&code?code:fallback}
function routeLabels(order:Order|null){if(!order||!Array.isArray(order.routePlan))return[];const names=new Set<string>();for(const step of order.routePlan){if(!step||typeof step!=="object")continue;const info=(step as {swapInfo?:unknown}).swapInfo;if(info&&typeof info==="object"&&typeof (info as {label?:unknown}).label==="string")names.add((info as {label:string}).label)}return [...names]}
function friendly(error:unknown){const text=error instanceof Error?error.message:String(error??"");if(/reject|cancel|denied/i.test(text))return"Transaction cancelled in wallet. No Solana swap was submitted.";if(text.includes("JUPITER_CUSTOM_API_HOST_NOT_ALLOWED"))return"This Jupiter host is not allowed by the PowerChain deployment. Use api.jup.ag or ask the operator to allow your provider hostname.";if(text.includes("JUPITER_CUSTOM_API_HOST_UNSAFE"))return"Local and IP-literal Jupiter provider targets are blocked in production.";if(text.includes("JUPITER_CUSTOM_API_KEY_REQUIRED")||text.includes("JUPITER_CUSTOM_API_KEY_INVALID"))return"Check your session Jupiter API key in Settings.";if(text.includes("JUPITER_API_KEY"))return"Jupiter routing needs a server key or your session key in Settings.";if(text.includes("API_KEY_REQUIRED")||text.includes("API_KEY_INVALID"))return"Check the PowerChain API key for your selected custom API.";if(text.includes("INSUFFICIENT"))return"Insufficient source-token balance.";return text||"Solana swap is temporarily unavailable."}
export function SolanaSwapInterface(){
 const { settings } = useUserSettings();
 const wallets=useConnectedWallets(),trusted=useTrustedTokens(),portfolio=usePortfolio(wallets.solanaAddress,null);const tokens=useMemo(()=>tokensForChain(trusted.tokens,"SOLANA"),[trusted.tokens]);
 const [fromId,setFromId]=useState("solana:sol"),[toId,setToId]=useState("solana:usdc"),[amount,setAmount]=useState(""),{slippageBps,setSlippageBps}=useSlippageTolerance(),[order,setOrder]=useState<Order|null>(null),[status,setStatus]=useState<"idle"|"routing"|"ready"|"signing"|"submitted"|"error">("idle"),[message,setMessage]=useState<string|null>(null),[signature,setSignature]=useState<string|null>(null);const controller=useRef<AbortController|null>(null);
 const effectiveSlippageBps=settings.swap.mevProtection?Math.min(slippageBps,100):slippageBps;
 const from=tokens.find(t=>t.id===fromId)??tokens[0],to=tokens.find(t=>t.id===toId)??tokens.find(t=>t.id!==from?.id)??tokens[0];const amountBase=from?toTokenBaseUnits(amount,from.decimals):null;const balance=portfolio.data?.balances.find(row=>row.tokenId===from?.id);const balanceBase=balance?.balanceBaseUnits??null;const insufficient=Boolean(amountBase&&balanceBase&&BigInt(amountBase)>BigInt(balanceBase));const providers=routeLabels(order);
 useEffect(()=>()=>controller.current?.abort(),[]);
 useEffect(()=>{setOrder(null);setSignature(null);setStatus("idle");setMessage(null)},[fromId,toId,amount,slippageBps,effectiveSlippageBps]);
 if(!from||!to||tokens.length<2)return <div className="pc-cinematic-panel rounded-[28px] p-6 text-sm text-slate-500">Trusted Solana swap assets are not fully configured.</div>;
 async function getRoute(){if(!wallets.solanaAddress||!amountBase||BigInt(amountBase)<=0n||from.id===to.id||insufficient)return;controller.current?.abort();const abort=new AbortController();controller.current=abort;setStatus("routing");setMessage(null);try{const response=await apiFetch("/api/v1/swap/solana/order",{method:"POST",headers:{"content-type":"application/json"},signal:abort.signal,body:JSON.stringify({payer:wallets.solanaAddress,inputMint:from.address,outputMint:to.address,amountBaseUnits:amountBase,slippageBps:effectiveSlippageBps})});const body:unknown=await response.json();const next=unwrap<Order>(body);if(!response.ok||!next)throw new Error(apiErrorCode(body,"JUPITER_ORDER_UNAVAILABLE"));setOrder(next);setStatus("ready")}catch(error){if(abort.signal.aborted)return;setStatus("error");setMessage(friendly(error))}}
 async function signAndExecute(){if(!order||!wallets.solanaAddress||!wallets.solanaSignTransaction)return;setStatus("signing");setMessage(null);try{if(order.payer!==wallets.solanaAddress)throw new Error("PAYER_CONNECTED_WALLET_MISMATCH");const tx=VersionedTransaction.deserialize(Uint8Array.from(atob(order.transaction),c=>c.charCodeAt(0)));const signed=await wallets.solanaSignTransaction(tx);const signedTransaction=btoa(String.fromCharCode(...signed.serialize()));const response=await apiFetch("/api/v1/swap/solana/execute",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({payer:wallets.solanaAddress,signedTransaction,requestId:order.requestId,lastValidBlockHeight:order.lastValidBlockHeight??null,inputMint:from.address,outputMint:to.address,amountBaseUnits:amountBase,slippageBps:effectiveSlippageBps,minimumOutputBaseUnits:order.otherAmountThreshold??null})});const body:unknown=await response.json();const data=unwrap<{signature?:string}>(body);if(!response.ok||!data?.signature)throw new Error(apiErrorCode(body,"JUPITER_EXECUTE_FAILED"));setSignature(data.signature);setStatus("submitted")}catch(error){setStatus("error");setMessage(friendly(error))}}
 function chooseFrom(token:TrustedToken){setFromId(token.id);if(token.id===toId){const replacement=tokens.find((item: TrustedToken)=>item.id!==token.id);if(replacement)setToId(replacement.id)}}function chooseTo(token:TrustedToken){setToId(token.id);if(token.id===fromId){const replacement=tokens.find((item: TrustedToken)=>item.id!==token.id);if(replacement)setFromId(replacement.id)}}
 return <section className="pc-cinematic-panel overflow-hidden rounded-[30px] border border-white/10 p-4 shadow-2xl sm:p-6" aria-label="Solana swap">
  <div className="flex items-center justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-white/55">Solana routing</p><h2 className="mt-1 text-xl font-semibold text-white">Jupiter Swap V2</h2></div><span className="rounded-full border border-white/10 bg-white/[.07] px-3 py-1.5 text-[10px] font-semibold text-white/70">Raydium · Meteora · Orca</span></div>
  <div className="mt-5 space-y-2"><div className="rounded-3xl border border-white/10 bg-black/25 p-4"><div className="flex items-end gap-3"><div className="min-w-0 flex-1"><label className="text-[10px] font-semibold uppercase tracking-[.14em] text-white/45" htmlFor="solana-swap-amount">You pay</label><input id="solana-swap-amount" inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="0.00" className="mt-2 w-full bg-transparent text-3xl font-semibold tracking-tight text-white outline-none placeholder:text-white/20"/></div><TokenSelector tokens={tokens} value={from} onChange={chooseFrom} label="Source token"/></div><div className="mt-3 flex items-center justify-between text-xs text-white/45"><span>Balance {portfolio.loading?"…":formatTokenAmount(balanceBase,from.decimals)} {from.symbol}</span>{from.symbol!=="SOL"&&balanceBase?<button type="button" onClick={()=>setAmount(formatTokenAmount(balanceBase,from.decimals,from.decimals))} className="font-semibold text-white/75 hover:text-white">Max</button>:null}</div></div>
  <button type="button" aria-label="Switch tokens" onClick={()=>{setFromId(to.id);setToId(from.id)}} className="mx-auto -my-4 grid size-10 place-items-center rounded-2xl border border-white/10 bg-[#0a100d] text-white shadow-xl transition hover:scale-105"><span aria-hidden="true">↓↑</span></button>
  <div className="rounded-3xl border border-white/10 bg-black/25 p-4"><div className="flex items-center justify-between gap-3"><div><p className="text-[10px] font-semibold uppercase tracking-[.14em] text-white/45">You receive</p><p className="mt-2 text-3xl font-semibold tracking-tight text-white">{order?formatTokenAmount(order.outAmount,to.decimals):"—"}</p></div><TokenSelector tokens={tokens} value={to} onChange={chooseTo} label="Destination token"/></div></div></div>
  <div className="mt-4 grid gap-2 rounded-2xl border border-white/10 bg-white/[.045] p-3 text-xs text-white/65 sm:grid-cols-2"><label className="flex items-center justify-between gap-3">Slippage <select value={slippageBps} onChange={e=>setSlippageBps(Number(e.target.value))} className="rounded-xl border border-white/10 bg-black/30 px-2 py-1.5 text-white">{SWAP_SLIPPAGE_PRESETS_BPS.map((bps)=><option key={bps} value={bps}>{formatSwapSlippagePercent(bps)}</option>)}</select></label><span className="flex items-center justify-between"><span>Network fee</span><strong className="text-white">Paid by wallet</strong></span>{order?<><span>Router <strong className="text-white">{order.router||"Jupiter"}</strong></span><span>Min received <strong className="text-white">{formatTokenAmount(order.otherAmountThreshold,to.decimals)} {to.symbol}</strong></span></>:null}</div>
  {providers.length?<div className="mt-3 flex flex-wrap gap-1.5" aria-label="DEX route">{providers.map(name=><span key={name} className="rounded-full border border-white/10 bg-white/[.05] px-2.5 py-1 text-[10px] text-white/65">{name}</span>)}</div>:null}
  {insufficient?<div className="mt-3"><TransactionMessage tone="error">Insufficient {from.symbol} balance.</TransactionMessage></div>:null}{message?<div className="mt-3"><TransactionMessage tone="error">{message}</TransactionMessage></div>:null}
  {signature?<div className="mt-3"><TransactionCompleted chain="SOLANA" digest={signature} explorerUrl={solscanTransactionUrl(signature)} label="Swap transaction submitted" finalityNotice="Submission is not Bridge settlement finality." /></div>:null}
  <button type="button" disabled={!wallets.solanaAddress||!amountBase||BigInt(amountBase||"0")<=0n||insufficient||status==="routing"||status==="signing"} onClick={order?()=>void signAndExecute():()=>void getRoute()} className="pc-button-primary mt-5 min-h-13 w-full rounded-2xl px-4 text-sm font-semibold disabled:cursor-not-allowed disabled:opacity-45">{!wallets.solanaAddress?"Connect Solana wallet":status==="routing"?"Finding best route…":status==="signing"?"Confirm in wallet…":order?"Sign & execute swap":"Review Solana route"}</button>
  <p className="mt-3 text-center text-[10px] leading-4 text-white/40">Jupiter assembles the route; the connected wallet signs it. {settings.jupiter.useCustomCredentials ? "Your session Jupiter credential is used for these requests." : "Server Jupiter credentials are used by default."} Pool and DEX labels are routing data, not bridge settlement evidence.</p>
 </section>
}
