[package]
name = "powerchain_staking"
version = "1.0.0"
description = "Deployment-gated PWRC Token-2022 fixed-pool staking program."
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "powerchain_staking"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]

[dependencies]
anchor-lang = "0.32.1"
anchor-spl = "0.32.1"
