import { PublicKey } from "@solana/web3.js";
import { normalizeChainAddress } from "@powerchain/blockchain";
import { persistWalletBalanceSnapshots } from "@powerchain/database";
import { solanaRpcRequest } from "../services/rpc";
import { trustedTokenList } from "../data/trusted-token-list";
import { getPowerChainSuiBalance } from "../sui/client";

type TokenAccountResponse={value:Array<{account:{data:{parsed?:{info?:{mint?:string;tokenAmount?:{amount?:string;decimals?:number}}}}}}>};
export async function fetchPortfolio(input:{solanaAddress?:string|null;suiAddress?:string|null}){const balances:Array<{tokenId:string;chain:"SOLANA"|"SUI";symbol:string;address:string;balanceBaseUnits:string;decimals:number}>=[];const errors:{solana?:string;sui?:string}={};if(input.solanaAddress){try{const owner=new PublicKey(input.solanaAddress).toBase58();const sol=await solanaRpcRequest<{value:number}>("getBalance",[owner,{commitment:"confirmed"}]);balances.push({tokenId:"solana:sol",chain:"SOLANA",symbol:"SOL",address:"So11111111111111111111111111111111111111112",balanceBaseUnits:String(sol.value),decimals:9});const accounts=await solanaRpcRequest<TokenAccountResponse>("getParsedTokenAccountsByOwner",[owner,{programId:"TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"},{encoding:"jsonParsed",commitment:"confirmed"}]);const accounts2=await solanaRpcRequest<TokenAccountResponse>("getParsedTokenAccountsByOwner",[owner,{programId:"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"},{encoding:"jsonParsed",commitment:"confirmed"}]);const totals=new Map<string,bigint>();for(const row of [...accounts.value,...accounts2.value]){const info=row.account.data.parsed?.info;const mint=info?.mint,amount=info?.tokenAmount?.amount;if(mint&&amount&&/^\d+$/.test(amount))totals.set(mint,(totals.get(mint)??0n)+BigInt(amount));}for(const token of trustedTokenList().filter(t=>t.chain==="SOLANA"&&!t.native))balances.push({tokenId:token.id,chain:"SOLANA",symbol:token.symbol,address:token.address,balanceBaseUnits:(totals.get(token.address)??0n).toString(),decimals:token.decimals});}catch(error){errors.solana=error instanceof Error?error.message:"SOLANA_PORTFOLIO_UNAVAILABLE"}}
if(input.suiAddress){try{const owner=normalizeChainAddress("SUI",input.suiAddress);const tokens=trustedTokenList().filter(t=>t.chain==="SUI");const rows=await Promise.all(tokens.map(async token=>({token,balance:await getPowerChainSuiBalance(owner,token.address)})));for(const row of rows)balances.push({tokenId:row.token.id,chain:"SUI",symbol:row.token.symbol,address:row.token.address,balanceBaseUnits:row.balance.balanceBaseUnits,decimals:row.token.decimals});}catch(error){errors.sui=error instanceof Error?error.message:"SUI_PORTFOLIO_UNAVAILABLE"}}
const checkedAt=new Date().toISOString();
try{await persistWalletBalanceSnapshots(balances.map((row)=>({wallet:row.chain==="SOLANA"?(input.solanaAddress??""):(input.suiAddress??""),chain:row.chain,asset:row.address,amountBaseUnits:row.balanceBaseUnits,decimals:row.decimals,source:"portfolio-runtime",observedAt:new Date(checkedAt)})).filter((row)=>row.wallet));}catch{}
return{wallets:{solana:input.solanaAddress??null,sui:input.suiAddress??null},balances,errors,status:Object.keys(errors).length===0?"ready":balances.length?"degraded":"unavailable",checkedAt,authoritativeForBridgeAccounting:false as const};}
