"use client";

import { useEffect, useRef, useState } from "react";
import { formatUtcTimestamp } from "../../lib/ui/activity-format";

export type TransactionDetail = { chain: "SOLANA" | "SUI" | string; id: string; title?: string; status?: string; timestamp?: string; explorerUrl?: string | null; source?: string | null; amountLabel?: string | null; };

export function TransactionDetailDrawer({ detail, open, onClose }: { detail: TransactionDetail | null; open: boolean; onClose: () => void }) {
  const closeRef = useRef<HTMLButtonElement>(null);
  const previousFocusRef = useRef<HTMLElement | null>(null);
  const [copyState, setCopyState] = useState<"idle"|"copied"|"failed">("idle");
  useEffect(() => { if (!open) return; previousFocusRef.current=document.activeElement instanceof HTMLElement?document.activeElement:null; const frame=requestAnimationFrame(()=>closeRef.current?.focus()); const onKeyDown=(event:KeyboardEvent)=>{if(event.key==="Escape")onClose();}; document.addEventListener("keydown",onKeyDown); return()=>{cancelAnimationFrame(frame);document.removeEventListener("keydown",onKeyDown);previousFocusRef.current?.focus();}; }, [open,onClose]);
  useEffect(()=>{setCopyState("idle");},[detail?.id]);
  if(!open||!detail)return null;
  async function copy(){try{if(!navigator.clipboard)throw new Error("clipboard unavailable");await navigator.clipboard.writeText(detail!.id);setCopyState("copied");}catch{setCopyState("failed");}}
  return <div className="fixed inset-0 z-50 flex items-end justify-center bg-slate-950/40 p-0 sm:items-center sm:p-6" role="presentation" onMouseDown={(event)=>{if(event.currentTarget===event.target)onClose();}}><section role="dialog" aria-modal="true" aria-labelledby="transaction-detail-title" aria-describedby="transaction-detail-description" className="max-h-[88dvh] w-full overflow-y-auto rounded-t-3xl bg-white p-5 shadow-2xl dark:bg-slate-950 sm:max-w-xl sm:rounded-3xl sm:p-6"><div className="flex items-start justify-between gap-4"><div><div className="text-xs font-semibold uppercase tracking-[0.14em] text-blue-600">{detail.chain}</div><h2 id="transaction-detail-title" className="mt-1 text-lg font-semibold text-slate-950 dark:text-white">{detail.title||"Transaction details"}</h2><p id="transaction-detail-description" className="mt-1 text-sm text-slate-500">Explorer/indexer data is for navigation and support, not bridge accounting evidence.</p></div><button ref={closeRef} type="button" onClick={onClose} aria-label="Close transaction details" className="min-h-10 min-w-10 rounded-xl border border-slate-200 px-3 text-sm font-semibold focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-500 dark:border-slate-700">Close</button></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><Field label="Status" value={detail.status||"Indexed"}/>{detail.timestamp?<Field label="Observed" value={formatUtcTimestamp(detail.timestamp)}/>:null}{detail.amountLabel?<Field label="Amount" value={detail.amountLabel}/>:null}{detail.source?<Field label="Source" value={detail.source}/>:null}<div className="sm:col-span-2 rounded-xl border border-slate-200 p-3 dark:border-slate-800"><div className="text-xs text-slate-500">Transaction</div><div className="mt-1 break-all font-mono text-xs text-slate-800 dark:text-slate-200">{detail.id}</div><button type="button" onClick={copy} className="mt-2 min-h-9 rounded-lg border border-slate-200 px-3 text-xs font-semibold text-blue-600 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-500 dark:border-slate-700">{copyState==="copied"?"Copied":copyState==="failed"?"Copy failed":"Copy transaction ID"}</button><span className="sr-only" aria-live="polite">{copyState==="copied"?"Transaction ID copied":copyState==="failed"?"Transaction ID could not be copied":""}</span></div></div>{detail.explorerUrl?<a href={detail.explorerUrl} target="_blank" rel="noreferrer" className="mt-5 inline-flex min-h-11 items-center justify-center rounded-xl bg-[#0B1730] px-4 text-sm font-semibold text-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-500">Open explorer ↗</a>:null}</section></div>;
}
function Field({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-slate-50 p-3 dark:bg-slate-900"><div className="text-xs text-slate-500">{label}</div><div className="mt-1 break-words text-sm font-medium text-slate-900 dark:text-slate-100">{value}</div></div>;}
