"use client";
import Link from "next/link";
import { useMemo } from "react";
import { useWalletPortfolio } from "@/hooks/use-wallet-portfolio";
import { useClaimEligibility } from "@/hooks/use-claim-eligibility";
import { usePwrcTransfers } from "@/hooks/use-pwrc-transfers";
const D=9;
function decimal(value:unknown){if(typeof value!=="string"||!/^\d+$/.test(value))return"0";const p=value.padStart(D+1,"0"),w=p.slice(0,-D).replace(/^0+(?=\d)/,"")||"0",f=p.slice(-D).replace(/0+$/,"");return f?`${w}.${f}`:w}
function short(v?:string|null){return v&&v.length>14?`${v.slice(0,6)}…${v.slice(-6)}`:v||"—"}
export function WalletPortfolioCard({solanaAddress,suiAddress}:{solanaAddress?:string|null;suiAddress?:string|null}){
 const portfolio=useWalletPortfolio(solanaAddress,suiAddress), eligibility=useClaimEligibility(solanaAddress||undefined), transfers=usePwrcTransfers(solanaAddress||undefined,5);
 const balances=portfolio.data?.balances,total=useMemo(()=>decimal(balances?.principalEquivalentBaseUnits),[balances?.principalEquivalentBaseUnits]);
 const claimable=useMemo(()=>decimal(eligibility.data?.claimableBaseUnits),[eligibility.data?.claimableBaseUnits]);
 const stale=Boolean(portfolio.data?.freshness?.solanaStale||portfolio.data?.freshness?.suiStale); const degraded=portfolio.data?.status==="degraded";
 return <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-950" aria-labelledby="wallet-portfolio-title">
  <div className="flex flex-col gap-3 border-b border-slate-200 p-5 dark:border-slate-800 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-[#294a3b]">Cross-chain wallet</p><h2 id="wallet-portfolio-title" className="mt-1 text-lg font-semibold">PWRC & wPWRC</h2><p className="mt-1 max-w-xl text-sm text-slate-600 dark:text-slate-400">Finalized wallet balances, claim readiness and recent PWRC activity across Solana and Sui.</p></div><div className="flex gap-2"><Link href="/bridge" className="min-h-10 rounded-xl bg-[#0b1511] px-3.5 py-2.5 text-sm font-semibold text-white">Bridge</Link><button type="button" onClick={()=>void Promise.all([portfolio.refresh(),eligibility.refresh(),transfers.refresh()])} className="min-h-10 rounded-xl border border-slate-200 px-3.5 text-sm font-semibold dark:border-slate-700">{portfolio.loading?"Refreshing…":"Refresh"}</button></div></div>
  {portfolio.error?<Notice tone="danger">{portfolio.error}</Notice>:null}{stale?<Notice tone="warning">Balance observations are stale. Refresh before starting a new bridge or claim action.</Notice>:null}{degraded?<Notice tone="warning">Partial provider degradation detected. Available chain data is still shown.</Notice>:null}
  <div className="grid gap-px bg-slate-200 dark:bg-slate-800 sm:grid-cols-2 xl:grid-cols-4"><Metric label="PWRC · Solana" value={`${decimal(balances?.solanaPwrcBaseUnits)} PWRC`} hint={short(solanaAddress)}/><Metric label="wPWRC · Sui" value={`${decimal(balances?.suiWpwrcBaseUnits)} wPWRC`} hint={short(suiAddress)}/><Metric label="Principal equivalent" value={`${total} PWRC`} hint="Wallet-level 1:1 equivalent"/><Metric label="Claimable" value={`${claimable} PWRC`} hint={eligibility.data?.status|| (solanaAddress?"Checking eligibility":"Connect Solana")}/></div>
  <div className="grid gap-4 p-5 lg:grid-cols-[.9fr_1.1fr]"><div className="rounded-xl border border-slate-200 p-4 dark:border-slate-800"><div className="flex items-center justify-between"><div><div className="text-sm font-semibold">PWRC ↔ wPWRC</div><div className="text-xs text-slate-500">Wormhole NTT · principal 1:1 · 1 PWRC ↔ 1 wPWRC principal</div></div><Link href="/assets" className="text-xs font-semibold text-[#294a3b]">Assets</Link></div><div className="mt-4 grid grid-cols-[1fr_auto_1fr] items-center gap-2"><Node chain="Solana" asset="PWRC" kind="Native"/><span className="text-center text-slate-400">↔</span><Node chain="Sui" asset="wPWRC" kind="Bridged"/></div><p className="mt-3 text-xs text-slate-500">Service fee and network gas are separate from destination principal.</p><div className="mt-3 flex gap-2"><Link href="/bridge" className="rounded-lg bg-[#173b2d] px-3 py-2 text-xs font-semibold text-white">Bridge assets</Link><Link href="/fees" className="rounded-lg border border-slate-200 px-3 py-2 text-xs font-semibold dark:border-slate-700">Fees</Link></div></div>
  <div className="overflow-hidden rounded-xl border border-slate-200 dark:border-slate-800"><div className="flex items-center justify-between border-b border-slate-200 px-4 py-3 dark:border-slate-800"><div><div className="text-sm font-semibold">Recent PWRC transfers</div><div className="text-xs text-slate-500">Finalized Helius transfer data when configured.</div></div><button type="button" onClick={()=>void transfers.refresh()} className="min-h-9 rounded-lg px-2 text-xs font-semibold">Refresh</button></div>{transfers.error?<div className="p-4 text-sm text-slate-500">{transfers.error}</div>:transfers.data?.transfers?.length?<div className="divide-y divide-slate-100 dark:divide-slate-900">{transfers.data.transfers.slice(0,5).map((r)=><a key={r.signature} href={r.explorerUrl} target="_blank" rel="noreferrer" className="grid grid-cols-[58px_1fr_auto] gap-2 px-4 py-3 text-sm hover:bg-slate-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-[#35584a] dark:hover:bg-slate-900"><span className="text-[11px] font-semibold uppercase text-slate-500">{r.direction}</span><span className="truncate font-mono text-xs">{short(r.signature)}</span><span className="tabular-nums">{decimal(r.amountBaseUnits)} PWRC</span></a>)}</div>:<div className="p-5 text-center text-sm text-slate-500">{transfers.loading?"Loading finalized transfers…":"No recent PWRC transfers found."}</div>}</div></div>
  <div className="flex flex-col gap-2 border-t border-slate-200 bg-slate-50 px-5 py-3 text-xs text-slate-500 dark:border-slate-800 dark:bg-slate-900/40 sm:flex-row sm:items-center sm:justify-between"><span>Claim eligibility is server-authoritative.</span><span>Wallet/indexer data is not bridge accounting evidence. Accounting authority: reconciliation.</span></div>
 </section>
}
function Metric({label,value,hint}:{label:string;value:string;hint:string}){return <div className="bg-white p-4 dark:bg-slate-950"><div className="text-xs font-semibold uppercase tracking-wide text-slate-500">{label}</div><div className="mt-2 truncate text-lg font-semibold tabular-nums" title={value}>{value}</div><div className="mt-1 truncate text-xs text-slate-500" title={hint}>{hint}</div></div>}
function Node({chain,asset,kind}:{chain:string;asset:string;kind:string}){return <div className="rounded-lg bg-slate-50 p-3 text-center dark:bg-slate-900"><div className="text-xs text-slate-500">{chain}</div><div className="font-semibold">{asset}</div><div className="text-[11px] text-[#294a3b]">{kind}</div></div>}
function Notice({tone,children}:{tone:"warning"|"danger";children:React.ReactNode}){const cls=tone==="danger"?"border-rose-200 bg-rose-50 text-rose-900 dark:border-rose-900/50 dark:bg-rose-950/20 dark:text-rose-200":"border-amber-200 bg-amber-50 text-amber-900 dark:border-amber-900/50 dark:bg-amber-950/20 dark:text-amber-200";return <div role={tone==="danger"?"alert":"status"} className={`mx-5 mt-4 rounded-xl border p-3 text-sm ${cls}`}>{children}</div>}
