"use client";

import Link from "next/link";
import { DataQualityBanner } from "./data-quality-banner";

export type WalletActionCenterProps = {
  solanaConnected: boolean; suiConnected: boolean; claimStatus?: string | null; claimableLabel?: string | null; stale?: boolean; degraded?: boolean; runtimeReady?: boolean; online?: boolean; walletChanged?: boolean; refreshing?: boolean; onRefresh?: () => void;
};

export function WalletActionCenter({ solanaConnected, suiConnected, claimStatus, claimableLabel, stale=false, degraded=false, runtimeReady=true, online=true, walletChanged=false, refreshing=false, onRefresh }: WalletActionCenterProps) {
  const connected = solanaConnected || suiConnected;
  const actionBlocked = !online || stale || degraded || !runtimeReady || walletChanged;
  const canBridge = connected && !actionBlocked;
  const claimEligible = solanaConnected && claimStatus === "ELIGIBLE";
  const quality = !online ? "offline" : stale || walletChanged ? "stale" : degraded ? "degraded" : runtimeReady ? "fresh" : "unavailable";
  return <section className="rounded-2xl border border-slate-200 bg-white p-4 dark:border-slate-800 dark:bg-slate-950 sm:p-5" aria-labelledby="wallet-actions-title"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-blue-600">Next action</p><h2 id="wallet-actions-title" className="mt-1 text-base font-semibold text-slate-950 dark:text-white">Bridge, claim or inspect activity</h2><p className="mt-1 max-w-2xl text-sm text-slate-600 dark:text-slate-400">New signatures require a connected wallet and fresh runtime data. Existing status remains available during incidents.</p></div>{onRefresh?<button type="button" disabled={refreshing||!online} onClick={onRefresh} className="min-h-10 shrink-0 rounded-xl border border-slate-200 px-3.5 text-sm font-semibold disabled:cursor-wait disabled:opacity-60 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-500 dark:border-slate-700 dark:text-slate-100">{refreshing?"Refreshing…":"Refresh data"}</button>:null}</div><div className="mt-4"><DataQualityBanner quality={quality} message={walletChanged?"Wallet identity changed. Refresh before bridge or claim.":undefined} /></div><div className="mt-4 grid gap-3 sm:grid-cols-3"><ActionCard title="Bridge assets" detail="PWRC ↔ wPWRC · principal 1:1" href="/bridge" primary enabled={canBridge} disabledReason={!connected?"Connect a wallet first":actionBlocked?"Refresh readiness first":undefined}/><ActionCard title={claimEligible?"Claim PWRC":"Claim status"} detail={claimEligible?`${claimableLabel||"Claimable PWRC"} available`:claimStatus||"Connect Solana to check"} href="/claim" enabled={solanaConnected} disabledReason={!solanaConnected?"Connect Solana first":undefined}/><ActionCard title="View history" detail="Solana + Sui wallet activity" href="/history" enabled={connected} disabledReason={!connected?"Connect a wallet first":undefined}/></div></section>;
}
function ActionCard({title,detail,href,enabled,disabledReason,primary=false}:{title:string;detail:string;href:string;enabled:boolean;disabledReason?:string;primary?:boolean}) { const content=<><span className="font-semibold">{title}</span><span className={`mt-1 text-xs ${primary&&enabled?"text-blue-100":"text-slate-500 dark:text-slate-400"}`}>{enabled?detail:disabledReason||detail}</span></>; if(!enabled)return <div aria-disabled="true" className="flex min-h-20 flex-col justify-center rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-slate-400 dark:border-slate-800 dark:bg-slate-900/40">{content}</div>; return <Link href={href} className={`flex min-h-20 flex-col justify-center rounded-xl px-4 py-3 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-500 ${primary?"bg-[#0B1730] text-white":"border border-slate-200 text-slate-900 hover:bg-slate-50 dark:border-slate-700 dark:text-slate-100 dark:hover:bg-slate-900"}`}>{content}</Link>; }
