"use client";
import Link from "next/link";
import {useOperationJournal} from "../../hooks/use-operation-journal";
import {useOperationStatusReconciler} from "../../hooks/use-operation-status-reconciler";
import {deriveOperationActionState} from "../../lib/bridge/operation-state";
import {operationAllowsDismiss,operationKindLabel,operationStatusLabel,operationStatusSummary} from "../../lib/bridge/operation-presentation";

function syncLabel(state:string){if(state==="syncing")return"Checking server…";if(state==="synced")return"Server synced";if(state==="offline")return"Offline";if(state==="conflict")return"Status conflict";return"Status recovery";}
export function OperationRecoveryCenter({currentWalletIdentity}:{currentWalletIdentity?:string}){
  const journal=useOperationJournal(),record=journal.record,sync=useOperationStatusReconciler(record);
  if(!record&&journal.externalConflict)return <section className="rounded-2xl border border-red-200 bg-red-50 p-4 dark:border-red-900/60 dark:bg-red-950/30" role="alert"><p className="text-sm font-semibold text-red-900 dark:text-red-100">Operation conflict</p><p className="mt-1 text-sm text-red-800 dark:text-red-200">Another tab has an active {operationKindLabel(journal.externalConflict.record.kind).toLowerCase()}. Open its status before starting another mutation.</p><div className="mt-3 flex flex-wrap gap-2"><Link href={journal.externalConflict.record.statusHref} className="inline-flex min-h-11 items-center justify-center rounded-xl bg-red-700 px-4 text-sm font-semibold text-white">Open other status</Link>{operationAllowsDismiss(journal.externalConflict.record.status)?<button type="button" onClick={journal.dismissExternalConflict} className="min-h-11 rounded-xl border border-red-300 px-4 text-sm font-semibold dark:border-red-800">Dismiss completed warning</button>:null}</div></section>;
  if(!record)return null;const action=deriveOperationActionState(record,currentWalletIdentity);
  return <section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm dark:border-slate-800 dark:bg-slate-950" aria-live="polite">
    <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">Existing operation</p>{record.statusApiHref?<span className="rounded-full border border-slate-200 px-2 py-0.5 text-[11px] font-medium text-slate-600 dark:border-slate-700 dark:text-slate-300">{syncLabel(sync.state)}</span>:null}</div>
    <h2 className="mt-1 text-sm font-semibold text-slate-950 dark:text-white">{operationKindLabel(record.kind)} · {operationStatusLabel(record.status)}</h2><p className="mt-1 break-all text-xs text-slate-500">{record.id}</p><p className="mt-2 text-sm text-slate-600 dark:text-slate-300">{operationStatusSummary(record.kind,record.status)}</p>
    {record.serverSnapshotId?<p className="mt-1 text-xs text-slate-500">Server snapshot {record.serverSnapshotId}</p>:null}{action.reason?<p className="mt-2 text-sm font-medium text-amber-700 dark:text-amber-300">{action.reason}</p>:null}
    {journal.externalConflict?<p className="mt-2 text-sm font-medium text-red-700 dark:text-red-300">Another tab has a different active operation. Resolve one operation before starting another mutation.</p>:null}{sync.state==="conflict"?<p className="mt-2 text-sm font-medium text-red-700 dark:text-red-300">Server status revision conflict detected. Use the status page and do not start another mutation.</p>:sync.error?<p className="mt-2 text-xs text-slate-500">Automatic status refresh is temporarily unavailable. The existing status link remains safe to use.</p>:null}</div>
    <div className="flex shrink-0 flex-wrap gap-2">{journal.externalConflict?<Link href={journal.externalConflict.record.statusHref} className="inline-flex min-h-11 items-center justify-center rounded-xl border border-red-300 px-4 text-sm font-semibold text-red-700 dark:border-red-800 dark:text-red-300">Other operation</Link>:null}<Link href={record.statusHref} className="inline-flex min-h-11 items-center justify-center rounded-xl bg-slate-950 px-4 text-sm font-semibold text-white focus:outline-none focus:ring-2 focus:ring-[#35584a] focus:ring-offset-2 dark:bg-white dark:text-slate-950">View status</Link>{record.statusApiHref?<button type="button" onClick={()=>void sync.refresh()} disabled={sync.state==="syncing"} className="min-h-11 rounded-xl border border-slate-300 px-4 text-sm font-semibold disabled:cursor-wait disabled:opacity-60 dark:border-slate-700">{sync.state==="syncing"?"Checking…":"Refresh status"}</button>:null}{action.terminal?<button type="button" onClick={journal.clear} className="min-h-11 rounded-xl border border-slate-300 px-4 text-sm font-semibold dark:border-slate-700">Dismiss</button>:null}</div></div>
  </section>;
}
