"use client";

import { useEffect, useMemo, useState } from "react";
import { useConnection, useWallet } from "@solana/wallet-adapter-react";
import { getAssociatedTokenAddressSync, TOKEN_2022_PROGRAM_ID } from "@solana/spl-token";
import { PublicKey } from "@solana/web3.js";
import type { StakingConfiguration, StakingStatus } from "@powerchain/staking";
import { useStakingPosition } from "@/hooks/use-staking-position";
import { useStakingRuntime } from "@/hooks/use-staking-runtime";
import { useStakingTransactionJournal } from "@/hooks/use-staking-transaction-journal";
import { SolanaStakingActions } from "./solana-staking-actions";
import { StakingTransactionRecovery } from "./staking-transaction-recovery";

const DECIMALS = 9;
function formatBaseUnits(value: string | undefined, maxFraction = 2): string {
  if (value === undefined) return "Unavailable";
  try {
    const amount = BigInt(value); const scale = 10n ** BigInt(DECIMALS); const whole = amount / scale; const fraction = (amount % scale).toString().padStart(DECIMALS, "0").slice(0, maxFraction).replace(/0+$/, "");
    return `${Number(whole).toLocaleString()}${fraction ? `.${fraction}` : ""}`;
  } catch { return "Unavailable"; }
}
function compactAddress(value: string | undefined): string { return value ? `${value.slice(0, 6)}…${value.slice(-6)}` : "UNSET"; }
function metricLabel(ready: boolean, value: string): string { return ready ? value : "Verification required"; }
function formatCheckedAt(value: string): string { const time = value.match(/T(\d{2}:\d{2}):/)?.[1]; return time ? `${time} UTC` : "recently"; }
function Icon({ name }: { name: "stake"|"rewards"|"shield"|"clock"|"wallet"|"check" }) {
  const paths = { stake:"M4 7h16M6 4h12v16H6zM9 11h6M9 15h6", rewards:"M12 3v18M5 8h14v11H5zM8 8c-2.5-3.5 3-5 4 0 1-5 6.5-3.5 4 0", shield:"M12 3 5 6v5c0 4.6 2.9 8.7 7 10 4.1-1.3 7-5.4 7-10V6l-7-3Zm-3 9 2 2 4-4", clock:"M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18Zm0 5v5l3 2", wallet:"M4 6h14v12H4zM17 10h3v4h-3", check:"m7 12 3 3 7-7" } as const;
  return <svg viewBox="0 0 24 24" className="size-5" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={paths[name]}/></svg>;
}

function StatusPill({ ready, paused }: { ready: boolean; paused?: boolean }) {
  const label = paused ? "Paused" : ready ? "RPC verified" : "Verification required";
  return <span className={`inline-flex items-center gap-2 rounded-full border px-3 py-1 text-xs font-semibold ${ready&&!paused?"border-[#b8c9c0] bg-[#edf4f0] text-[#244b3b] dark:border-[#35584a] dark:bg-[#173b2d]/30 dark:text-[#d9e3de]":"border-slate-200 bg-slate-50 text-slate-600 dark:border-white/10 dark:bg-white/[0.04] dark:text-slate-300"}`}><span className={`size-1.5 rounded-full ${ready&&!paused?"bg-[#35584a]":"bg-slate-400"}`}/>{label}</span>;
}

export function StakingDashboard({ initialStatus }: { initialStatus: StakingStatus }) {
  const { status, loading: runtimeLoading, error: runtimeError, refresh: refreshRuntime } = useStakingRuntime(initialStatus);
  const solana = status.configurations.find((item) => item.chain === "SOLANA") ?? initialStatus.configurations.find((item) => item.chain === "SOLANA");
  const sui = status.configurations.find((item) => item.chain === "SUI") ?? initialStatus.configurations.find((item) => item.chain === "SUI");
  if (!solana || !sui) throw new Error("STAKING_CONFIGURATION_INCOMPLETE");
  const { publicKey, connected } = useWallet(); const { connection } = useConnection(); const wallet = publicKey?.toBase58();
  const [refreshKey,setRefreshKey]=useState(0); const { position, loading:positionLoading, error:positionError }=useStakingPosition(wallet,refreshKey); const transactionJournal=useStakingTransactionJournal(wallet); const [walletBalance,setWalletBalance]=useState<string|undefined>(); const [walletBalanceError,setWalletBalanceError]=useState<string|null>(null); const [walletBalanceLoading,setWalletBalanceLoading]=useState(false);
  const ready=solana.executable&&solana.paused!==true; const reward=solana.rewardSource; const metrics=solana.poolMetrics;
  const mint=solana.identifiers.find((item)=>item.name==="mint")?.value; const program=solana.identifiers.find((item)=>item.name==="program")?.value; const config=solana.identifiers.find((item)=>item.name==="config")?.value;
  useEffect(()=>{ let cancelled=false; async function load(){ if(!publicKey||!mint||!ready){setWalletBalance(undefined);setWalletBalanceError(null);setWalletBalanceLoading(false);return;} setWalletBalanceLoading(true);setWalletBalanceError(null); try{const ata=getAssociatedTokenAddressSync(new PublicKey(mint),publicKey,false,TOKEN_2022_PROGRAM_ID); const account=await connection.getAccountInfo(ata,"confirmed"); if(cancelled)return; if(!account){setWalletBalance("0");return;} const result=await connection.getTokenAccountBalance(ata,"confirmed"); if(!cancelled)setWalletBalance(result.value.amount);}catch(reason){if(!cancelled){setWalletBalance(undefined);setWalletBalanceError(reason instanceof Error?reason.message:"Unable to read wallet PWRC balance.");}}finally{if(!cancelled)setWalletBalanceLoading(false);}} void load(); return()=>{cancelled=true}; },[connection,mint,publicKey,ready,refreshKey]);
  const snapshot=position?.snapshot; const totalStaked=formatBaseUnits(metrics?.totalStakedBaseUnits); const availableRewards=formatBaseUnits(reward.availableBaseUnits); const funded=formatBaseUnits(reward.fundedBaseUnits); const yourStake=formatBaseUnits(snapshot?.stakedBaseUnits); const pending=formatBaseUnits(snapshot?.pendingUnstakeBaseUnits); const rewards=formatBaseUnits(snapshot?.accruedRewardsBaseUnits); const minimum=formatBaseUnits(metrics?.minStakeBaseUnits);
  const cards=useMemo(()=>[
    {icon:"stake" as const,label:"Total staked",value:metricLabel(ready,`${totalStaked} PWRC`),detail:ready?"Verified program config":"No synthetic TVL"},
    {icon:"rewards" as const,label:"Reward vault available",value:metricLabel(ready,`${availableRewards} PWRC`),detail:ready?`${funded} PWRC funded`:"Fixed-pool evidence required"},
    {icon:"shield" as const,label:"Deployment",value:ready?"Executable":"Fail closed",detail:ready?"Program + config + vaults verified":"Wallet actions disabled"},
    {icon:"clock" as const,label:"Cooldown",value:metrics?`${metrics.cooldownSlots} slots`:"Unavailable",detail:metrics?"On-chain config":"Not estimated"},
  ],[availableRewards,funded,metrics,ready,totalStaked]);

  return <div className="space-y-6">
    <section className="staking-hero relative overflow-hidden rounded-[28px] border border-slate-200 bg-white px-5 py-7 shadow-[0_24px_70px_rgba(7,16,13,.08)] sm:px-8 sm:py-10 dark:border-white/10 dark:bg-[#07100d] dark:shadow-[0_32px_90px_rgba(0,0,0,.34)]">
      <div className="staking-grid-pattern absolute inset-0 opacity-60" aria-hidden="true"/><div className="relative grid gap-8 lg:grid-cols-[1.2fr_.8fr] lg:items-center">
        <div><div className="flex flex-wrap items-center gap-2"><StatusPill ready={ready} paused={solana.paused}/><span className="text-[11px] text-slate-500">{runtimeLoading?"Refreshing verification…":`Checked ${formatCheckedAt(status.checkedAt)}`}</span><button type="button" onClick={()=>void refreshRuntime()} className="rounded-lg border border-slate-200 bg-white px-2.5 py-1 text-[11px] font-semibold text-slate-600 hover:border-[#557568] dark:border-white/10 dark:bg-white/[0.03] dark:text-slate-300">Refresh</button></div><p className="mt-5 text-xs font-semibold uppercase tracking-[.18em] text-[#35584a] dark:text-[#adc0b6]">PowerChain staking</p><h1 className="mt-2 max-w-2xl text-4xl font-semibold tracking-[-.04em] text-slate-950 sm:text-5xl dark:text-white">Stake PWRC.<br/><span className="text-[#35584a] dark:text-[#adc0b6]">Wallet controlled.</span></h1><p className="mt-4 max-w-xl text-sm leading-6 text-slate-600 sm:text-base dark:text-slate-300">A verified fixed-pool staking flow for canonical Token-2022 PWRC. No invented APY, validator ranking, reward forecast, or custody layer.</p><div className="mt-6 flex flex-wrap gap-3"><a href="#stake-workspace" className="pc-button-primary rounded-xl px-5 py-3 text-sm font-semibold">Open staking workspace</a><a href="#deployment" className="pc-button-light rounded-xl px-5 py-3 text-sm font-semibold">View verification</a></div></div>
        <div className="relative mx-auto grid size-64 place-items-center sm:size-72"><div className="absolute inset-3 rounded-full border border-[#557568]/30 bg-[#eef4f1] shadow-[0_0_80px_rgba(41,74,59,.12)] dark:bg-[#0b1712] dark:shadow-[0_0_90px_rgba(71,111,92,.16)]"/><div className="absolute inset-9 rounded-full border border-[#557568]/30"/><div className="relative grid size-40 place-items-center rounded-full border-[10px] border-[#dfe8e3] bg-[#102019] text-white shadow-2xl dark:border-[#31463c]"><span className="text-5xl font-black italic tracking-[-.08em]">P</span><span className="absolute bottom-7 text-[9px] font-semibold uppercase tracking-[.25em] text-[#adc0b6]">PWRC</span></div><div className="absolute bottom-1 rounded-full border border-[#bdcbc4] bg-white/90 px-4 py-2 text-xs font-semibold text-[#244b3b] shadow-lg backdrop-blur dark:border-white/10 dark:bg-[#0b1511]/90 dark:text-[#d9e3de]">{ready?"On-chain verified":"Execution gated"}</div></div>
      </div>
    </section>

    {runtimeError?<div role="status" className="rounded-2xl border border-amber-200 bg-amber-50 px-4 py-3 text-xs text-amber-800 dark:border-amber-900/40 dark:bg-amber-950/20 dark:text-amber-200">Latest staking verification refresh failed. Existing data remains visible, but signing still performs a fresh fail-closed verification. {runtimeError}</div>:null}

    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{cards.map((card)=><article key={card.label} className="pc-panel rounded-2xl p-4"><div className="flex items-start gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-[#edf4f0] text-[#35584a] dark:bg-[#173b2d]/35 dark:text-[#adc0b6]"><Icon name={card.icon}/></span><div className="min-w-0"><p className="text-xs text-slate-500">{card.label}</p><p className="mt-1 truncate text-lg font-semibold text-slate-950 dark:text-white">{card.value}</p><p className="mt-1 text-[11px] text-slate-500">{card.detail}</p></div></div></article>)}</section>

    <section id="stake-workspace" className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_340px]">
      <article className="pc-panel rounded-[24px] p-5 sm:p-6"><div className="flex flex-col gap-3 border-b border-slate-200 pb-5 sm:flex-row sm:items-start sm:justify-between dark:border-white/10"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-[#35584a] dark:text-[#adc0b6]">PWRC position</p><h2 className="mt-1 text-xl font-semibold text-slate-950 dark:text-white">Stake, unstake and claim</h2><p className="mt-1 text-sm text-slate-500">Every transaction is rebuilt from fresh deployment verification before your wallet signs.</p></div><StatusPill ready={ready} paused={solana.paused}/></div><div className="mt-6"><SolanaStakingActions configuration={solana} position={position} walletBalanceBaseUnits={walletBalance} onConfirmed={()=>{setRefreshKey((value)=>value+1);void refreshRuntime();void transactionJournal.reconcile();}} onSubmitted={transactionJournal.recordSubmitted}/></div></article>
      <aside className="space-y-4"><article className="pc-panel rounded-[24px] p-5"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-[#edf4f0] text-[#35584a] dark:bg-[#173b2d]/35 dark:text-[#adc0b6]"><Icon name="wallet"/></span><div><p className="text-xs text-slate-500">Your verified position</p><p className="text-sm font-semibold text-slate-950 dark:text-white">{connected?compactAddress(wallet):"Wallet not connected"}</p></div></div><dl className="mt-5 space-y-3 text-sm"><div className="flex justify-between gap-4"><dt className="text-slate-500">Wallet PWRC</dt><dd className="font-semibold text-slate-900 dark:text-white">{connected?(walletBalanceLoading?"Loading…":walletBalance===undefined?"Unavailable":`${formatBaseUnits(walletBalance)} PWRC`):"—"}</dd></div><div className="flex justify-between gap-4"><dt className="text-slate-500">Active stake</dt><dd className="font-semibold text-slate-900 dark:text-white">{positionLoading?"Loading…":position?.exists?`${yourStake} PWRC`:"0 PWRC"}</dd></div><div className="flex justify-between gap-4"><dt className="text-slate-500">Pending unstake</dt><dd className="font-semibold text-slate-900 dark:text-white">{position?.exists?`${pending} PWRC`:"0 PWRC"}</dd></div><div className="flex justify-between gap-4"><dt className="text-slate-500">Recorded rewards</dt><dd className="font-semibold text-slate-900 dark:text-white">{position?.exists?`${rewards} PWRC`:"0 PWRC"}</dd></div></dl>{walletBalanceError?<p className="mt-4 text-xs text-amber-700 dark:text-amber-300">Wallet balance unavailable: {walletBalanceError}</p>:null}{positionError?<p className="mt-2 text-xs text-red-700 dark:text-red-300">{positionError}</p>:null}<p className="mt-4 rounded-xl bg-slate-50 px-3 py-2 text-[11px] leading-5 text-slate-500 dark:bg-white/[0.04]">Recorded rewards are read from the wallet-owned on-chain position. This interface does not convert the configured reward policy into APY or forecast future earnings.</p></article>
      <article className="rounded-[24px] border border-[#bdcbc4] bg-[#f3f7f5] p-5 dark:border-[#35584a]/40 dark:bg-[#102019]"><p className="text-xs font-semibold uppercase tracking-[.15em] text-[#35584a] dark:text-[#adc0b6]">Policy</p><p className="mt-2 text-lg font-semibold text-slate-950 dark:text-white">Fixed reward pool</p><p className="mt-2 text-sm leading-6 text-slate-600 dark:text-slate-300">{ready?`${availableRewards} PWRC currently available in the verified reward vault.`:"Funding remains unavailable until deployment evidence verifies."}</p>{reward.rate?<p className="mt-3 text-xs text-slate-500">Configured rate: {reward.rate.ppmPerEpoch} ppm per {reward.rate.epochSlots} slots. This is not presented as APR/APY.</p>:null}</article></aside>
    </section>

    <StakingTransactionRecovery journal={transactionJournal}/>

    <section id="deployment" className="grid gap-5 lg:grid-cols-2"><article className="pc-panel rounded-[24px] p-5 sm:p-6"><h2 className="text-lg font-semibold text-slate-950 dark:text-white">Deployment verification</h2><p className="mt-2 text-sm leading-6 text-slate-500">Execution becomes available only after one RPC endpoint verifies the full deployment proof.</p><div className="mt-5 grid gap-3 sm:grid-cols-2">{[["Program",program],["Config",config],["Stake vault",solana.identifiers.find((i)=>i.name==="stake-vault")?.value],["Reward vault",reward.sourceIdentifier]].map(([label,value])=><div key={label} className="rounded-xl border border-slate-200 bg-slate-50 p-3 dark:border-white/10 dark:bg-white/[0.03]"><p className="text-[11px] font-semibold uppercase tracking-[.12em] text-slate-500">{label}</p><p className="mt-1 break-all font-mono text-xs text-slate-700 dark:text-slate-300">{compactAddress(value)}</p></div>)}</div><p className="mt-4 text-xs leading-5 text-slate-500">{solana.deploymentEvidence.detail}</p></article>
    <article className="pc-panel rounded-[24px] p-5 sm:p-6"><h2 className="text-lg font-semibold text-slate-950 dark:text-white">Runtime parameters</h2><dl className="mt-5 space-y-3 text-sm"><div className="flex justify-between gap-4"><dt className="text-slate-500">Minimum stake</dt><dd className="font-semibold text-slate-900 dark:text-white">{metrics?`${minimum} PWRC`:"Unavailable"}</dd></div><div className="flex justify-between gap-4"><dt className="text-slate-500">Cooldown</dt><dd className="font-semibold text-slate-900 dark:text-white">{metrics?`${metrics.cooldownSlots} slots`:"Unavailable"}</dd></div><div className="flex justify-between gap-4"><dt className="text-slate-500">Custody</dt><dd className="font-semibold text-slate-900 dark:text-white">{solana.custodyModel}</dd></div><div className="flex justify-between gap-4"><dt className="text-slate-500">Sui wPWRC</dt><dd className="font-semibold text-slate-900 dark:text-white">{sui.executable?"Verified":"Fail-closed"}</dd></div></dl><p className="mt-4 text-xs leading-5 text-slate-500">Sui staking stays unavailable until package, pool, reward source and runtime ownership/funding are independently verified.</p></article></section>

    <section className="grid gap-5 lg:grid-cols-2"><article className="pc-panel rounded-[24px] p-5 sm:p-6"><h2 className="text-lg font-semibold text-slate-950 dark:text-white">Why the staking flow is safer</h2><div className="mt-5 grid gap-4 sm:grid-cols-2">{[["Wallet authority","Your connected wallet signs every state-changing instruction."],["Runtime verification","Program, config, canonical mint and vaults are checked before execution."],["Funded rewards","Rewards originate from a verified program vault, not newly invented UI values."],["No synthetic APY","The interface exposes the configured ppm/epoch policy without converting it into a marketing APY."]].map(([title,detail])=><div key={title} className="flex gap-3"><span className="mt-0.5 grid size-7 shrink-0 place-items-center rounded-full bg-[#edf4f0] text-[#35584a] dark:bg-[#173b2d]/35 dark:text-[#adc0b6]"><Icon name="check"/></span><div><p className="text-sm font-semibold text-slate-900 dark:text-white">{title}</p><p className="mt-1 text-xs leading-5 text-slate-500">{detail}</p></div></div>)}</div></article><article className="pc-panel rounded-[24px] p-5 sm:p-6"><h2 className="text-lg font-semibold text-slate-950 dark:text-white">How staking works</h2><ol className="mt-5 space-y-4">{[["1","Connect wallet","Use the supported Solana wallet provider."],["2","Verify deployment","PowerChain checks the complete staking deployment against RPC."],["3","Initialize position","Create the wallet-owned staking PDA if it does not exist."],["4","Sign action","Stake, request unstake, withdraw, or claim with explicit wallet approval."]].map(([number,title,detail])=><li key={number} className="flex gap-3"><span className="grid size-8 shrink-0 place-items-center rounded-full bg-[#173b2d] text-xs font-bold text-white dark:bg-[#d9e3de] dark:text-[#102019]">{number}</span><div><p className="text-sm font-semibold text-slate-900 dark:text-white">{title}</p><p className="mt-1 text-xs leading-5 text-slate-500">{detail}</p></div></li>)}</ol></article></section>
  </div>;
}
