import { prisma } from "@powerchain/database/prisma";
import { assertServiceFeeVerified } from "../fees/settlement";
import { verifyBridgeChainTransaction } from "./rpc";
import { findNttOperationForTransfer, vaaHash } from "./wormholescan";

const activeStatuses = ["SOURCE_SUBMITTED","SOURCE_FINALIZED","MESSAGE_OBSERVED","DESTINATION_SUBMITTED","DESTINATION_FINALIZED","RECONCILIATION_REQUIRED"] as const;
export async function claimBridgeTransferBatch(input:{workerId:string;limit:number;leaseMs:number}) { const now=new Date(); const candidates=await prisma.bridgeTransfer.findMany({where:{status:{in:[...activeStatuses]},AND:[{OR:[{bridgeNextRetryAt:null},{bridgeNextRetryAt:{lte:now}}]},{OR:[{bridgeWorkerLeaseUntil:null},{bridgeWorkerLeaseUntil:{lt:now}}]}]},orderBy:{updatedAt:"asc"},take:Math.max(1,Math.min(100,input.limit))}); const claimed=[]; for(const row of candidates){ const result=await prisma.bridgeTransfer.updateMany({where:{id:row.id,OR:[{bridgeWorkerLeaseUntil:null},{bridgeWorkerLeaseUntil:{lt:now}}]},data:{bridgeWorkerLeaseOwner:input.workerId,bridgeWorkerLeaseUntil:new Date(Date.now()+input.leaseMs)}}); if(result.count===1) claimed.push(row); } return claimed; }
export async function releaseBridgeTransferLease(id:string,workerId:string){await prisma.bridgeTransfer.updateMany({where:{id,bridgeWorkerLeaseOwner:workerId},data:{bridgeWorkerLeaseOwner:null,bridgeWorkerLeaseUntil:null}});}
function retryDelay(attempt:number){return Math.min(300_000,5_000*2**Math.min(6,attempt));}
export async function recordBridgeTransferRetry(id:string,workerId:string,error:string){const row=await prisma.bridgeTransfer.findUnique({where:{id},select:{bridgeAttemptCount:true}}); const attempt=(row?.bridgeAttemptCount??0)+1; await prisma.bridgeTransfer.updateMany({where:{id,bridgeWorkerLeaseOwner:workerId},data:{bridgeAttemptCount:attempt,bridgeNextRetryAt:new Date(Date.now()+retryDelay(attempt)),bridgeWorkerLeaseOwner:null,bridgeWorkerLeaseUntil:null,failureCode:error.slice(0,160)}});}

export async function processBridgeTransfer(id:string){ const row=await prisma.bridgeTransfer.findUnique({where:{id},include:{quote:true}}); if(!row) throw new Error("TRANSFER_NOT_FOUND"); const principal=row.principalBaseUnits.toFixed(0);
 if(row.status==="SOURCE_SUBMITTED"){if(!row.sourceTx) throw new Error("SOURCE_TX_REQUIRED"); const evidence=await verifyBridgeChainTransaction({direction:row.direction,role:"source",txHash:row.sourceTx,wallet:row.sourceAddress,principalBaseUnits:principal}); await prisma.bridgeTransfer.update({where:{id},data:{status:"SOURCE_FINALIZED",sourceVerifiedAt:new Date(),sourceFinalityRef:JSON.stringify(evidence.evidence),failureCode:null,bridgeNextRetryAt:null}}); return;}
 if(row.status==="SOURCE_FINALIZED"||row.status==="MESSAGE_OBSERVED"){if(!row.sourceTx) throw new Error("SOURCE_TX_REQUIRED"); const op=await findNttOperationForTransfer({direction:row.direction,sourceTx:row.sourceTx,principalBaseUnits:principal,sourceAddress:row.sourceAddress,destinationAddress:row.destinationAddress}); if(!op) throw new Error("WORMHOLE_NTT_OPERATION_PENDING"); const data={wormholeOperationId:op.operationId,wormholeEmitterChain:op.emitterChain,wormholeEmitter:op.emitterAddress,wormholeSequence:op.sequence,wormholeVaaHash:vaaHash(op.vaaRaw),messageObservedAt:new Date(),failureCode:null,bridgeNextRetryAt:null}; if(op.destinationTx){await prisma.bridgeTransfer.update({where:{id},data:{...data,destinationTx:op.destinationTx,status:"DESTINATION_SUBMITTED"}});}else{await prisma.bridgeTransfer.update({where:{id},data:{...data,status:"MESSAGE_OBSERVED"}});} return;}
 if(row.status==="DESTINATION_SUBMITTED"){if(!row.destinationTx) throw new Error("DESTINATION_TX_REQUIRED"); const evidence=await verifyBridgeChainTransaction({direction:row.direction,role:"destination",txHash:row.destinationTx,wallet:row.destinationAddress,principalBaseUnits:principal}); await prisma.bridgeTransfer.update({where:{id},data:{status:"DESTINATION_FINALIZED",destinationVerifiedAt:new Date(),destinationFinalityRef:JSON.stringify(evidence.evidence),failureCode:null,bridgeNextRetryAt:null}}); return;}
 if(row.status==="DESTINATION_FINALIZED"||row.status==="RECONCILIATION_REQUIRED"){if(!row.sourceVerifiedAt||!row.destinationVerifiedAt||!row.wormholeOperationId||!row.sourceTx||!row.destinationTx) {await prisma.bridgeTransfer.update({where:{id},data:{status:"RECONCILIATION_REQUIRED",failureCode:"FINALITY_EVIDENCE_INCOMPLETE"}});return;} try{await assertServiceFeeVerified(id);}catch(error){if(error instanceof Error && error.message === "SERVICE_FEE_NOT_VERIFIED") throw new Error("SERVICE_FEE_VERIFICATION_PENDING");throw error;} const op=await findNttOperationForTransfer({direction:row.direction,sourceTx:row.sourceTx,principalBaseUnits:principal,sourceAddress:row.sourceAddress,destinationAddress:row.destinationAddress}); if(!op||op.operationId!==row.wormholeOperationId||op.destinationTx!==row.destinationTx){await prisma.bridgeTransfer.update({where:{id},data:{status:"RECONCILIATION_REQUIRED",failureCode:"WORMHOLE_RECONCILIATION_MISMATCH"}});return;} await prisma.bridgeTransfer.update({where:{id},data:{status:"COMPLETED",reconciliationEvidence:{kind:"POWERCHAIN_NTT_TRANSFER_RECONCILIATION",operationId:op.operationId,sourceTx:row.sourceTx,destinationTx:row.destinationTx,principalBaseUnits:principal,fromChain:op.fromChain,toChain:op.toChain,vaaHash:vaaHash(op.vaaRaw),sourceVerifiedAt:row.sourceVerifiedAt.toISOString(),destinationVerifiedAt:row.destinationVerifiedAt.toISOString(),reconciledAt:new Date().toISOString()},failureCode:null,bridgeNextRetryAt:null}}); }
}
