import { createHash } from "node:crypto";
import { PublicKey } from "@solana/web3.js";
import { normalizeSuiAddress } from "@mysten/sui/utils";
import { directionChains, nttBridgeConfig } from "./config";
import type { BridgeDirection, WormholeNttObservation } from "./types";

type RawOperation = {
  id?: string; emitterChain?: number; emitterAddress?: { hex?:string; native?:string }; sequence?:string;
  vaa?: { raw?:string }; sourceChain?: { transaction?:{txHash?:string};status?:string }; targetChain?:{transaction?:{txHash?:string};status?:string};
  content?: { standarizedProperties?: { fromChain?:number;toChain?:number;fromAddress?:string;toAddress?:string;amount?:string }; payload?: { nttMessage?: { trimmedAmount?:{amount?:string;decimals?:number} } } };
};
function universal(chain:"SOLANA"|"SUI", address:string) { if(chain==="SOLANA") return Buffer.from(new PublicKey(address).toBytes()).toString("hex"); return normalizeSuiAddress(address).slice(2).padStart(64,"0"); }
function normalizeAmount(op:RawOperation) { const t=op.content?.payload?.nttMessage?.trimmedAmount; if(t && /^\d+$/.test(t.amount??"") && Number.isInteger(t.decimals) && t.decimals!>=0 && t.decimals!<=9) return (BigInt(t.amount!)*(10n**BigInt(9-t.decimals!))).toString(); const a=op.content?.standarizedProperties?.amount; if(a && /^\d+$/.test(a)) return a; return null; }
function addressMatches(chain:"SOLANA"|"SUI", observed:string|undefined, expected:string) { if(!observed) return false; const clean=observed.toLowerCase().replace(/^0x/,""); const uni=universal(chain,expected).toLowerCase(); if(clean===uni) return true; try { return chain==="SOLANA" ? new PublicKey(observed).toBase58()===new PublicKey(expected).toBase58() : normalizeSuiAddress(observed)===normalizeSuiAddress(expected); } catch { return false; } }
async function getOperations(address:string) { const config=nttBridgeConfig(); const controller=new AbortController(); const timer=setTimeout(()=>controller.abort(),10_000); try { const u=new URL(`${config.wormholeScanBaseUrl}/operations`); u.searchParams.set("address",address);u.searchParams.set("pageSize","50"); const r=await fetch(u,{headers:{accept:"application/json"},signal:controller.signal,cache:"no-store"}); if(!r.ok) throw new Error(`WORMHOLESCAN_HTTP_${r.status}`); const body=await r.json() as {operations?:RawOperation[]}; return body.operations??[]; } finally {clearTimeout(timer);} }

export async function findNttOperationForTransfer(input:{direction:BridgeDirection;sourceTx:string;principalBaseUnits:string;sourceAddress:string;destinationAddress:string}):Promise<WormholeNttObservation|null>{
 const cfg=nttBridgeConfig(); const chains=directionChains(input.direction); const src=chains.source==="SOLANA"?cfg.solana:cfg.sui; const dst=chains.destination==="SOLANA"?cfg.solana:cfg.sui; const ops=await getOperations(src.emitter);
 for(const op of ops){ if(op.sourceChain?.transaction?.txHash!==input.sourceTx) continue; const p=op.content?.standarizedProperties; const amount=normalizeAmount(op); if(!op.id||!op.sequence||!p||amount===null) throw new Error("WORMHOLE_NTT_OPERATION_MALFORMED"); if(p.fromChain!==src.chainId||p.toChain!==dst.chainId) throw new Error("WORMHOLE_NTT_CHAIN_MISMATCH"); if((op.emitterChain??src.chainId)!==src.chainId) throw new Error("WORMHOLE_NTT_EMITTER_CHAIN_MISMATCH"); const observedEmitter=op.emitterAddress?.native??op.emitterAddress?.hex; if(observedEmitter&&!addressMatches(chains.source,observedEmitter,src.emitter)) throw new Error("WORMHOLE_NTT_EMITTER_MISMATCH"); if(p.fromAddress&&!addressMatches(chains.source,p.fromAddress,input.sourceAddress)) throw new Error("WORMHOLE_NTT_SOURCE_MISMATCH"); if(amount!==input.principalBaseUnits) throw new Error("WORMHOLE_NTT_AMOUNT_MISMATCH"); if(!addressMatches(chains.destination,p.toAddress,input.destinationAddress)) throw new Error("WORMHOLE_NTT_DESTINATION_MISMATCH"); const emitter=op.emitterAddress?.native??op.emitterAddress?.hex??src.emitter; const vaa=op.vaa?.raw??null; const destinationTx=op.targetChain?.transaction?.txHash??null; if(!vaa&&!destinationTx) throw new Error("WORMHOLE_NTT_ATTESTATION_PENDING"); return {operationId:op.id,emitterChain:op.emitterChain??src.chainId,emitterAddress:emitter,sequence:op.sequence,sourceTx:input.sourceTx,destinationTx,vaaRaw:vaa,fromChain:p.fromChain,toChain:p.toChain,fromAddress:p.fromAddress??input.sourceAddress,toAddress:p.toAddress??input.destinationAddress,normalizedAmountBaseUnits:amount,sourceStatus:op.sourceChain?.status??null,destinationStatus:op.targetChain?.status??null}; }
 return null;
}
export function vaaHash(raw:string|null){return raw?createHash("sha256").update(raw).digest("hex"):null;}
